### PR TITLE
Start CI pipeline on Travis CI

### PR DESCRIPTION
**Pull request by MoriTanosuke**
Trying to implement  #12.

I started a build pipeline on Travis. In my branch I added a simple `.travis.yml` with a couple of settings matching the project.

Unfortunately there is a gradle task which tries to run an emulator, which is not fully supported  (see https://docs.travis-ci.com/user/languages/android/#How-to-Create-and-Start-an-Emulator).

    Execution failed for task ':FDAndroidClient:connectedDebugAndroidTest'.
    > com.android.builder.testing.api.DeviceException: No connected devices!

Maybe you can use it anyway, or disable the gradle task for CI builds. There is also a way to upload build artifacts to Github Releases, documentation at https://docs.travis-ci.com/user/deployment/releases/ I started to use this in another project of mine, but it needs some private set up, so I can only give some tips if you get stuck.

If you have any questions, feel free to ask in the comments. 😄

### CODE REVIEW

**Comment by mcicolella** [comment]
@MoriTanosuke any tip for uploading build artifact is welcome.

**Comment by MoriTanosuke** [comment]
You have to provide your own Github OAuth token, read about it here https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token

Here's a short description of the steps to update the `.travis.yml` for releases:

# install the *travis command line client* https://github.com/travis-ci/travis.rb#installation
# run `travis setup releases` in the project directory, this should add the `deploy` section to `.travis.yml`
# modify the `deploy` section to match the artifact you want to deploy:
````
deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  file: "build/path/to/your/file.jar"
  skip_cleanup: true
  on:
    tags: true
````

**Comment by MoriTanosuke** [comment]
I updated my `.travis.yml`with an example and enabled release uploads in my repository. Have a look at [this build][0] for an example, the uploaded release is [here][1]. The sourcecode is attached by Github whenever you create a release, the files *FDAndroidClient-release-unsigned.apk* and *FDAndroidClient-debug.apk* are uploaded by Travis.

[0]: https://travis-ci.org/MoriTanosuke/fd-android-client/builds/292484931
[1]: https://github.com/MoriTanosuke/fd-android-client/releases/tag/example-release

**Comment by mcicolella** [comment]
@MoriTanosuke Sorry for delay. You made a great work! If you update your branch to fix a conflict about .gitignore I can merge this PR and then update the files with our Travis configuration.
Thanks a lot.

**Comment by MoriTanosuke** [comment]
@mcicolella Rebased and resolved.

**Pull request merged**
